### ISSUE TITLE
Adding admin dashboard

### ISSUE THREAD

**Issue by ahmed-fawzy-metwally** [Hossam-Tarek/tech-shop#12]
Adding an admin dashboard.
That allows the website owner to add, delete, or update a product or category. and view the message received from users via contact us.  Besides the possibility of notifications that tell the owner what has already been done.
![Screenshot from 2020-10-18 18-51-33](https://user-images.githubusercontent.com/36691001/96374435-21264700-1173-11eb-942d-547450e0e338.png)

**Comment by Hossam-Tarek** [comment]
You've done a great job.
