### ISSUE TITLE
How to initialize user data object

### ISSUE THREAD

**Issue by Hossam-Tarek** [Hossam-Tarek/tech-shop#16]
First of all The initialization of the `UserData` object when the user is signing up
There are 3 mandatory variables `(name, email, password)`
```javascript
try {
    let user = new UserData("Hossam Tarek", "hossamtarek250@gmail.com", "01203910920");
} catch (error) {
    console.log(error.message);
}
```
Then save this object in the local storage to be a permanent user of our website.
This is how to get the `JSON` representation of the object
```javascript
let userString = JSON.stringfy(user.getObject());
```
Finally here is how to get our object back.
```javascript
let user = UserData.setObject(userString);
```

**Comment by ahmed-fawzy-metwally** [comment]
could you tell me your local storage keyName your are saved users in it?

**Comment by Hossam-Tarek** [comment]
The local and session storage key name is `UserData`
and there is no id the id will be the email address of the user

**Comment by ahmed-fawzy-metwally** [comment]
Thanks a lot.
