### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Hossam-Tarek** [Hossam-Tarek/tech-shop#24]
@EleneMalak2020  After all the work we've done. Now the README.md file is too short and also the description in it about our website.

Add more description to the file and a screenshot of the main page of the website.

This task will take place on your fork on Github, not on your local machine.

If you don't know how to modify this file online on Github, send to me a message, and I will tell you how you can do it?

**Comment by Hossam-Tarek** [comment]
@EleneMalak2020

**Comment by EleneMalak2020** [comment]
I have added more details to the README.md file and i will try to add sample of the website later.
Thanks for your help.

**Comment by Hossam-Tarek** [comment]
Thanks for your effort.I'll add it.
