### ISSUE TITLE
Button goes nowhere

### ISSUE THREAD

**Issue by Hossam-Tarek** [Hossam-Tarek/tech-shop#27]
@MahmoudShalma  When clicking the button it goes nowhere. Please add this behavior when clicking on the button will go to `product-details.html` page for all card in all pages that you've worked on e.g. `iphone.html`, `back-bag.html`, `printer.html` etc.

![Screenshot from 2020-10-19 13-20-11](https://user-images.githubusercontent.com/23726675/96444183-1ec4fb00-120e-11eb-94f7-587513a40c34.png)

**Comment by MahmoudShalma** [comment]
Ok
