### ISSUE TITLE
Signup not working

### ISSUE THREAD

**Issue by Hossam-Tarek** [Hossam-Tarek/tech-shop#29]
@MahmoudShalma When I click on the `Sign Up` button, nothing happens at all or even saves the data in the local storage, or even do validation of any type. It's a silent button.

![Screenshot from 2020-10-19 14-07-31](https://user-images.githubusercontent.com/23726675/96451046-4a98ae80-1217-11eb-811c-f3c6b962e1e4.png)

**Comment by ahmed-fawzy-metwally** [comment]
The same reason as 
[Admin sidebar bug #30](https://github.com/Hossam-Tarek/tech-shop/issues/30#issue-724595101)
