### ISSUE TITLE
Admin sidebar bug

### ISSUE THREAD

**Issue by Hossam-Tarek** [Hossam-Tarek/tech-shop#30]
@AhmedFawzyMetwaly The two items specified in the image below `Category`, `Product` when clicking on them they go nowhere. Or even showing it's content. Simply it's a silent button.

![Screenshot from 2020-10-19 14-01-18](https://user-images.githubusercontent.com/23726675/96454009-8fbedf80-121b-11eb-87b1-b1a54748190a.png)

**Comment by ahmed-fawzy-metwally** [comment]
If you view the console you will get the error.
```
Access to script at 'file:///home/User/Gitirectory/tech-shop/js/admin.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, brave, chrome-untrusted, https.
```
that because redirect I have done. as if the user opens the login page and the user logged in then will redirect to the home page instead of staying on the login page.
as this 
```javascript 
window.location.href = '/admin-login.html'; 
```
To solve that you should use a live server.
