### ISSUE TITLE
Adding fontawesome

### ISSUE THREAD

**Issue by ahmed-fawzy-metwally** [Hossam-Tarek/tech-shop#4]
Add font-awesome files and index with it.
Font Awesome is a font and icon toolkit based on CSS and Less.
Font Awesome has a 38% market share among those websites that use third-party font scripts on their platform, ranking it second place after Google Fonts.
```html
<link rel="stylesheet" href="css/fontaswesme-all.min.css">
```

**Comment by MahmoudShalma** [comment]
tmam

**Comment by EleneMalak2020** [comment]
well done..thanks for your effort
